services:
    mysql:
        container_name: "mysql"
        image: mysql:8.0
        volumes:
            - ./database/oai_db.sql:/docker-entrypoint-initdb.d/oai_db.sql
            - ./healthscripts/mysql-healthcheck.sh:/tmp/mysql-healthcheck.sh
        environment:
            - TZ=Europe/Paris
            - MYSQL_DATABASE=oai_db
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
            - MYSQL_ROOT_PASSWORD=linux
        healthcheck:
            test: /bin/bash -c "/tmp/mysql-healthcheck.sh"
            interval: 5s
            timeout: 2s
            retries: 10
        networks:
            core_network:
                ipv4_address: 192.168.0.2
                interface_name: eth0
                
    ims:
        container_name: "ims"
        image: oaisoftwarealliance/ims:latest
        volumes:
            - ./conf/sip.conf:/etc/asterisk/sip.conf
            - ./conf/users.conf:/etc/asterisk/users.conf
        healthcheck:
            test: /bin/bash -c "pgrep asterisk"
            interval: 5s
            timeout: 2s
            retries: 10
        networks:
            core_network:
                ipv4_address: 192.168.0.3
                interface_name: eth0
    
    oai-nrf:
        container_name: "oai-nrf"
        image: oaisoftwarealliance/oai-nrf:develop
        expose:
            - 80/tcp
            - 8080/tcp
        volumes:
            - ./conf/config.yaml:/openair-nrf/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        networks:
            core_network:
                ipv4_address: 192.168.0.4
                interface_name: eth0

    oai-udr:
        container_name: "oai-udr"
        image: oaisoftwarealliance/oai-udr:develop
        expose:
            - 80/tcp
            - 8080/tcp
        volumes:
            - ./conf/config.yaml:/openair-udr/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        depends_on:
            - mysql
            - oai-nrf
        networks:
            core_network:
                ipv4_address: 192.168.0.5
                interface_name: eth0
    
    oai-udm:
        container_name: "oai-udm"
        image: oaisoftwarealliance/oai-udm:develop
        expose:
            - 80/tcp
            - 8080/tcp
        volumes:
            - ./conf/config.yaml:/openair-udm/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        depends_on:
            - oai-udr
        networks:
            core_network:
                ipv4_address: 192.168.0.6
                interface_name: eth0

    oai-ausf:
        container_name: "oai-ausf"
        image: oaisoftwarealliance/oai-ausf:develop
        expose:
            - 80/tcp
            - 8080/tcp
        volumes:
            - ./conf/config.yaml:/openair-ausf/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        depends_on:
            - oai-udm
        networks:
            core_network:
                ipv4_address: 192.168.0.7
                interface_name: eth0
    
    oai-amf:
        container_name: "oai-amf"
        image: oaisoftwarealliance/oai-amf:develop
        expose:
            - 80/tcp
            - 8080/tcp
            - 38412/sctp
        volumes:
            - ./conf/config.yaml:/openair-amf/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        depends_on:
            - mysql
            - oai-nrf
            - oai-ausf
        networks:
            core_network:
                ipv4_address: 192.168.0.8
                interface_name: eth0

    oai-smf:
        container_name: "oai-smf"
        image: oaisoftwarealliance/oai-smf:develop
        expose:
            - 80/tcp
            - 8080/tcp
            - 8805/udp
        volumes:
            - ./conf/config.yaml:/openair-smf/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        depends_on:
            - oai-nrf
            - oai-amf
        networks:
            core_network:
                ipv4_address: 192.168.0.9
                interface_name: eth0

    oai-upf:
        container_name: "oai-upf"
        image: oaisoftwarealliance/oai-upf:develop
        expose:
            - 2152/udp
            - 8805/udp
        entrypoint: /bin/bash -c \
              "ip route del default via 192.168.0.1 dev eth0;"\
              "ip route add default via 192.168.6.11 dev eth1;"\
              "/openair-upf/bin/oai_upf -c /openair-upf/etc/config.yaml -o" # Check this line
        volumes:
            - ./conf/config.yaml:/openair-upf/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        depends_on:
            - oai-nrf
            - oai-smf
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        networks:
            core_network:
                ipv4_address: 192.168.0.10
                interface_name: eth0
            n6_network:
                ipv4_address: 192.168.6.10
                interface_name: eth1
            

    oai-ext-dn:
        privileged: true
        init: true
        container_name: oai-ext-dn
        image: oaisoftwarealliance/trf-gen-cn5g:jammy
        entrypoint: /bin/bash -c \
              "iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE;"\
              "echo 1 > /proc/sys/net/ipv4/ip_forward; sleep infinity"
        healthcheck:
            test: /bin/bash -c "ping -c 2 192.168.6.10"
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            n6_network:
                ipv4_address: 192.168.6.11
                interface_name: eth0
            inter_net:
                ipv4_address: 192.168.1.11
                interface_name: eth1

    # phpmyadmin:
    #     image: phpmyadmin/phpmyadmin:latest
    #     restart: unless-stopped
    #     environment:
    #         - PMA_HOST=mysql
    #         - PMA_PORT=3306
    #         - MYSQL_ROOT_PASSWORD=linux
    #     ports:
    #         - "8080:80"
    #     depends_on:
    #         mysql:
    #             condition: service_started
    #     networks:
    #         core_network:
    #             ipv4_address: 192.168.0.200

networks:
    core_network:
        driver: bridge
        name: core_network
        ipam:
            config:
                - subnet: 192.168.0.0/24
        driver_opts:
            com.docker.network.bridge.name: "core_network"
    
    inter_net:
        driver: bridge
        name: inter_net
        ipam:
            config:
                - subnet: 192.168.1.0/24
        driver_opts:
            com.docker.network.bridge.name: "inter_net"
    
    n6_network:
        driver: bridge
        name: n6_network
        ipam:
            config:
                - subnet: 192.168.6.0/24
        driver_opts:
            com.docker.network.bridge.name: "n6_network"

