import json
import re
import os
import sys
from langgraph.prebuilt import create_react_agent
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage
from langchain_ollama import ChatOllama

# Add the src folder to path so we can import from tools
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from tools.workspace.workspace_tools import workspace_tools

MODULE_4_SYSTEM_PROMPT = """You are "Module 4: The Data Scientist" in an automated xApp development pipeline.
Your job is to train a Machine Learning model using the historical dataset generated by Module 3, and save the trained model to disk.

CRITICAL RULES - NO NETWORK CODE:
You do NOT write FlexRIC, E2, or real-time networking code. Your ONLY job is to write a standard Python ML training script that reads a CSV, trains a model, and saves it.

--- STRICT WORKFLOW INSTRUCTIONS ---
You must use your tools to execute the following steps in order:

1. CREATE DIRECTORY: Create a folder named `ml/` inside the workspace.
2. DATA EXPLORATION: You must understand the data before choosing an algorithm. Use `terminal_command` to run a Python one-liner to inspect the first few rows of the historical training data.
   - Example: `python3 -c "import pandas as pd; df=pd.read_csv('data/historical_training_data.csv'); print(df.head()); print(df.columns)"`
3. CHOOSE ALGORITHM: Based on `Intent_Blueprint.cycle_Type` (Supervised vs Unsupervised) and your data exploration, select a standard, lightweight ML algorithm (e.g., Random Forest, Isolation Forest, K-Means, or a simple PyTorch/TensorFlow Neural Network).
4. WRITE SCRIPT: Write `ml/train.py`. The script MUST:
   - Load `data/historical_training_data.csv`.
   - Preprocess the data (handle missing values, scale features if needed).
   - Train the model using the selected algorithm.
   - Save the trained model to disk (e.g., `import joblib; joblib.dump(model, 'ml/saved_model.pkl')`).
5. EXECUTE SCRIPT: Run `python3 ml/train.py`. If it crashes (e.g., shape mismatch), read the error, fix the script, and run it again.

--- RESPONSE FORMAT ---
ONLY after the script has executed successfully and the model file exists in the `ml/` directory, output a final JSON block updating the blueprint with the model details.

```json
{
  "ML_Model_Artifacts": {
    "model_path": "ml/saved_model.pkl",
    "technique_used": "string (e.g., 'IsolationForest for Unsupervised Anomaly Detection')",
    "expected_input_features": ["list of exact column names the model expects for inference"]
  }
}
```
"""

def get_llm():
    ollama_url = os.getenv("OLLAMA_URL", "http://localhost:11434")
    ollama_model = os.getenv("OLLAMA_MODEL", "llama3.1")
    return ChatOllama(model=ollama_model, base_url=ollama_url)

def module_4_ml_dev_node(state: dict) -> dict:
    """Module 4: Trains an ML model and saves the artifact."""
    
    blueprint = state.get("blueprint", {})
    
    # We pass the paths to the data so the agent knows exactly where to look
    data_paths = blueprint.get("Data_Paths", {})
    hist_data = data_paths.get("historical_training_data_path", "data/historical_training_data.csv")
    
    prompt_content = (
        f"Here is the complete Blueprint:\n{json.dumps(blueprint, indent=2)}\n\n"
        f"The training data is located at: `{hist_data}`.\n\n"
        f"Create the `ml/` directory, explore the data, choose an algorithm, train the model, "
        f"save it, and return the ML_Model_Artifacts JSON.\n"
        f"IMPORTANT: Create a `log/` directory in the workspace and save the terminal output of your script execution to `log/module_4_ml.log` using your tools."
    )
    
    llm = get_llm()
    
    # Create the ReAct agent
    ml_agent = create_react_agent(
        model=llm, 
        tools=workspace_tools, 
        prompt=MODULE_4_SYSTEM_PROMPT
    )
    
    try:
        # Recursion limit of 10-20 to allow for data exploration, coding, and debugging
        recursion_limit = int(os.getenv("RECURSIVE_LIMIT", 20))
        result = ml_agent.invoke(
            {"messages": [HumanMessage(content=prompt_content)]},
            {"recursion_limit": recursion_limit}
        )
        final_text = result["messages"][-1].content
        
    except Exception as e:
        print(f"Module 4 Error (ML Training): {e}")
        return {"messages": [AIMessage(content=f"ML Training failed: {e}")]}

    # Extract the JSON block
    ml_artifacts = {}
    json_match = re.search(r'```json\s*(.*?)\s*```', final_text, re.DOTALL)
    if json_match:
        try:
            parsed = json.loads(json_match.group(1))
            ml_artifacts = parsed.get("ML_Model_Artifacts", {})
            blueprint["ML_Model_Artifacts"] = ml_artifacts
        except json.JSONDecodeError:
            print("Failed to parse JSON from Module 4 output.")
            pass

    return {
        "blueprint": blueprint,
        "messages": [AIMessage(content=final_text)]
    }
