import json
import re
import os
import sys
from typing import Any, Dict
from langgraph.prebuilt import create_react_agent
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage
from langchain_ollama import ChatOllama

# Add the src folder to path so we can import from tools
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from tools.workspace.workspace_tools import workspace_tools, WORKSPACE_DIR

DEFAULT_ACCEPTANCE_THRESHOLD = 0.85
DEFAULT_METRIC_POLICY = "task_aware"
DEFAULT_MAX_TRAINING_ATTEMPTS = 5

MODULE_4_SYSTEM_PROMPT = """You are "Module 4: The Data Scientist" in an automated xApp development pipeline.
Your job is to train, evaluate, improve, and save the best Machine Learning model using the training and test datasets generated by Module 3.

CRITICAL RULES - NO NETWORK CODE:
You do NOT write FlexRIC, E2, or real-time networking code. Your ONLY job is to write a standard Python ML training script that reads a CSV, trains a model, and saves it.
Only save the best model to `ml/saved_model.pkl`. Do not leave weaker candidate model files behind.

--- STRICT WORKFLOW INSTRUCTIONS ---
You must use your tools to execute the following steps in order:

1. CREATE DIRECTORY: Create a folder named `ml/` inside the workspace.
2. DATA EXPLORATION: Inspect the train and test data before choosing an algorithm. Run ONE combined one-liner:
   python3 -c "
import pandas as pd
train=pd.read_csv('data/historical_training_data.csv')
test=pd.read_csv('data/test_data.csv')
print('TRAIN shape:', train.shape, 'cols:', train.columns.tolist())
print('TEST shape:', test.shape, 'cols:', test.columns.tolist())
if 'label' in train.columns: print('Label dist:', train['label'].value_counts().to_dict())
"
3. READ ACCEPTANCE CRITERIA from the blueprint provided in your prompt:
   - `Intent_Blueprint.model_acceptance_criteria.threshold` (default 0.85 if missing/null)
   - `Intent_Blueprint.model_acceptance_criteria.metric_policy` (default `task_aware` if missing)
4. CHOOSE MODEL FAMILY:
   - Supervised_ML: prefer a lightweight sklearn RandomForestClassifier or LogisticRegression pipeline.
   - Unsupervised_ML anomaly: use IsolationForest or OneClassSVM.
   - For autoencoder-style requirements, train on normal data, score reconstruction error on test data.
5. WRITE `ml/train.py`. The script MUST:
   a. Load training and test CSVs.
   b. Feature columns = all columns except `label`, `ue_id`, `timestamp`, `time`, `index`, `id`.
   c. Preprocess with a pipeline (imputer + scaler + estimator).
   d. Train up to MAX_TRAINING_ATTEMPTS configurations (env var, default 3).
   e. After EACH attempt, immediately overwrite `ml/evaluation_report.json` with the CURRENT best result.
      This ensures the report is always on disk even if the script is interrupted.
      Format: {"threshold": <float>, "metric_policy": <str>, "best_metric_name": <str>,
               "best_metric_value": <float>, "threshold_met": <bool>, "technique_used": <str>,
               "expected_input_features": [<list>], "evaluation_report_path": "ml/evaluation_report.json",
               "attempts": [{"attempt": N, "model": <str>, "metric_name": <str>, "metric_value": <float>, "threshold_met": <bool>}]}
   f. Save only the BEST candidate to `ml/saved_model.pkl` using joblib.
6. TASK-AWARE EVALUATION POLICY:
   - Supervised with labels: use accuracy by default; F1 if labels are imbalanced.
   - Unsupervised with labeled test: use anomaly F1 (1=anomaly, 0=normal).
   - No labels on test: use a quality metric but mark `threshold_met` as advisory in the report.
7. EXECUTE: Run `python3 ml/train.py`. If it crashes, read stderr, fix the script, and re-run ONCE.
   Do NOT re-run more than once if the script itself completes but the metric is below threshold — the
   evaluation_report.json already records the miss, which is sufficient.
8. VERIFY: After the script exits, run:
   python3 -c "import json; r=open('ml/evaluation_report.json').read(); print(r[:500])"
   Confirm `ml/evaluation_report.json` exists and contains valid JSON.

--- RESPONSE FORMAT ---
After step 8, output the final JSON block. Read values FROM `ml/evaluation_report.json`
(do NOT compute or call Python inside this block — use literal values only).

IMPORTANT: The ```json block must contain ONLY literal JSON values (strings, numbers,
booleans, arrays of strings). Do NOT write Python expressions, variable names, function
calls, or code inside the JSON block. Every value must be a constant you read from the
evaluation report file.

```json
{
  "ML_Model_Artifacts": {
    "model_path": "ml/saved_model.pkl",
    "technique_used": "string (e.g., 'RandomForestClassifier for Supervised_ML')",
    "expected_input_features": ["col1", "col2"],
    "best_metric_name": "accuracy | f1 | anomaly_f1 | other",
    "best_metric_value": 0.91,
    "threshold": 0.85,
    "threshold_met": true,
    "evaluation_report_path": "ml/evaluation_report.json"
  }
}
```
"""

def get_llm():
    ollama_url = os.getenv("OLLAMA_URL", "http://localhost:11434")
    ollama_model = os.getenv("OLLAMA_MODEL", "llama3.1")
    return ChatOllama(model=ollama_model, base_url=ollama_url)

def _coerce_threshold(value: Any) -> float:
    try:
        threshold = float(value)
    except (TypeError, ValueError):
        return DEFAULT_ACCEPTANCE_THRESHOLD
    if threshold <= 0:
        return DEFAULT_ACCEPTANCE_THRESHOLD
    if threshold > 1:
        return threshold / 100.0 if threshold <= 100 else DEFAULT_ACCEPTANCE_THRESHOLD
    return threshold

def ensure_model_acceptance_defaults(blueprint: Dict[str, Any]) -> Dict[str, Any]:
    """Backfill model acceptance criteria so older blueprints remain valid."""
    intent = blueprint.setdefault("Intent_Blueprint", {})
    criteria = intent.get("model_acceptance_criteria")
    if not isinstance(criteria, dict):
        criteria = {}

    criteria["threshold"] = _coerce_threshold(criteria.get("threshold", DEFAULT_ACCEPTANCE_THRESHOLD))
    criteria["metric_policy"] = criteria.get("metric_policy") or DEFAULT_METRIC_POLICY
    criteria.setdefault(
        "metric_description_NL",
        "Task-aware model quality: supervised accuracy/F1, anomaly F1 for labeled anomaly tests, or reconstruction/separation quality for autoencoder-style workflows."
    )
    intent["model_acceptance_criteria"] = criteria
    return blueprint

def _finalize_ml_artifacts(artifacts: Dict[str, Any], blueprint: Dict[str, Any]) -> Dict[str, Any]:
    criteria = blueprint.get("Intent_Blueprint", {}).get("model_acceptance_criteria", {})
    threshold = _coerce_threshold(criteria.get("threshold", DEFAULT_ACCEPTANCE_THRESHOLD))
    artifacts.setdefault("model_path", "ml/saved_model.pkl")
    artifacts.setdefault("evaluation_report_path", "ml/evaluation_report.json")
    artifacts.setdefault("threshold", threshold)
    artifacts.setdefault("threshold_met", False)
    artifacts.setdefault("best_metric_name", "unknown")
    artifacts.setdefault("best_metric_value", None)
    artifacts.setdefault("expected_input_features", [])
    return artifacts

def _get_max_training_attempts() -> int:
    try:
        attempts = int(os.getenv("MAX_TRAINING_ATTEMPTS", DEFAULT_MAX_TRAINING_ATTEMPTS))
    except ValueError:
        return DEFAULT_MAX_TRAINING_ATTEMPTS
    return attempts if attempts > 0 else DEFAULT_MAX_TRAINING_ATTEMPTS

def _write_fallback_report(blueprint: Dict[str, Any], error_msg: str) -> None:
    """Write a minimal evaluation_report.json when the agent crashes or exhausts its limit."""
    criteria = blueprint.get("Intent_Blueprint", {}).get("model_acceptance_criteria", {})
    threshold = _coerce_threshold(criteria.get("threshold", DEFAULT_ACCEPTANCE_THRESHOLD))
    report = {
        "status": "AGENT_FAILED",
        "error": error_msg[:500],
        "threshold": threshold,
        "metric_policy": criteria.get("metric_policy", DEFAULT_METRIC_POLICY),
        "threshold_met": False,
        "best_metric_name": None,
        "best_metric_value": None,
        "technique_used": None,
        "expected_input_features": [],
        "evaluation_report_path": "ml/evaluation_report.json",
        "attempts": [],
        "note": "Module 4 agent did not complete. Increase ML_RECURSIVE_LIMIT or check logs."
    }
    ml_dir = os.path.join(WORKSPACE_DIR, "ml")
    os.makedirs(ml_dir, exist_ok=True)
    report_path = os.path.join(ml_dir, "evaluation_report.json")
    if not os.path.exists(report_path):
        with open(report_path, "w") as f:
            json.dump(report, f, indent=2)

def _recover_artifacts_from_workspace(blueprint: Dict[str, Any]) -> Dict[str, Any]:
    """Read ml/evaluation_report.json from workspace and populate ML_Model_Artifacts."""
    report_path = os.path.join(WORKSPACE_DIR, "ml", "evaluation_report.json")
    model_path = os.path.join(WORKSPACE_DIR, "ml", "saved_model.pkl")
    if not os.path.exists(report_path):
        return blueprint
    try:
        with open(report_path) as f:
            report = json.load(f)
        artifacts = {
            "model_path": "ml/saved_model.pkl" if os.path.exists(model_path) else None,
            "technique_used": report.get("technique_used"),
            "expected_input_features": report.get("expected_input_features", []),
            "best_metric_name": report.get("best_metric_name"),
            "best_metric_value": report.get("best_metric_value"),
            "threshold": report.get("threshold", DEFAULT_ACCEPTANCE_THRESHOLD),
            "threshold_met": report.get("threshold_met", False),
            "evaluation_report_path": "ml/evaluation_report.json",
        }
        blueprint["ML_Model_Artifacts"] = _finalize_ml_artifacts(artifacts, blueprint)
        print(f"Module 4: recovered artifacts from workspace — threshold_met={artifacts['threshold_met']}, metric={artifacts['best_metric_value']}")
    except Exception as e:
        print(f"Module 4: artifact recovery failed: {e}")
    return blueprint

def module_4_ml_dev_node(state: dict) -> dict:
    """Module 4: Trains an ML model and saves the artifact."""

    blueprint = ensure_model_acceptance_defaults(state.get("blueprint", {}))

    data_paths = blueprint.get("Data_Paths", {})
    hist_data = data_paths.get("historical_training_data_path", "data/historical_training_data.csv")
    test_data = data_paths.get("test_data_path", "data/test_data.csv")
    criteria = blueprint.get("Intent_Blueprint", {}).get("model_acceptance_criteria", {})
    threshold = criteria.get("threshold", DEFAULT_ACCEPTANCE_THRESHOLD)
    metric_policy = criteria.get("metric_policy", DEFAULT_METRIC_POLICY)
    max_attempts = _get_max_training_attempts()

    prompt_content = (
        f"Here is the complete Blueprint:\n{json.dumps(blueprint, indent=2)}\n\n"
        f"Training data: `{hist_data}` | Test data: `{test_data}`\n"
        f"Acceptance threshold: `{threshold}` | Metric policy: `{metric_policy}` | Max attempts: `{max_attempts}`\n\n"
        f"Follow the workflow: create ml/ dir, explore data in ONE combined one-liner, write ml/train.py "
        f"(which writes ml/evaluation_report.json after every attempt), run it, fix once if it crashes, "
        f"verify the report, and return the ML_Model_Artifacts JSON.\n"
        f"IMPORTANT: Also save terminal output to log/module_4_ml.log."
    )

    llm = get_llm()
    ml_agent = create_react_agent(model=llm, tools=workspace_tools, prompt=MODULE_4_SYSTEM_PROMPT)

    final_text = ""
    try:
        # ML_RECURSIVE_LIMIT defaults to 40; falls back to RECURSIVE_LIMIT if that env var is set higher
        recursion_limit = int(os.getenv("ML_RECURSIVE_LIMIT", max(80, int(os.getenv("RECURSIVE_LIMIT", 20)))))
        result = ml_agent.invoke(
            {"messages": [HumanMessage(content=prompt_content)]},
            {"recursion_limit": recursion_limit}
        )
        final_text = result["messages"][-1].content
    except Exception as e:
        error_msg = str(e)
        print(f"Module 4 Error (ML Training): {error_msg}")
        _write_fallback_report(blueprint, error_msg)
        blueprint = _recover_artifacts_from_workspace(blueprint)
        return {
            "blueprint": blueprint,
            "messages": [AIMessage(content=f"ML Training agent failed: {error_msg}")]
        }

    # Try to extract ML_Model_Artifacts from the agent's final JSON block
    json_match = re.search(r'```json\s*(.*?)\s*```', final_text, re.DOTALL)
    if json_match:
        try:
            parsed = json.loads(json_match.group(1))
            ml_artifacts = _finalize_ml_artifacts(parsed.get("ML_Model_Artifacts", {}), blueprint)
            blueprint["ML_Model_Artifacts"] = ml_artifacts
        except json.JSONDecodeError:
            print("Module 4: failed to parse JSON from agent output, recovering from workspace.")
            blueprint = _recover_artifacts_from_workspace(blueprint)
    else:
        # Agent finished but didn't emit JSON — read the report file directly
        print("Module 4: no JSON block in agent output, recovering from workspace.")
        blueprint = _recover_artifacts_from_workspace(blueprint)

    return {
        "blueprint": blueprint,
        "messages": [AIMessage(content=final_text)]
    }
