import json
import re
import os
import sys
import copy
from typing import Any, Dict, Optional
from langgraph.prebuilt import create_react_agent
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage
from langchain_ollama import ChatOllama

# Add the src folder to path so we can import from tools
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from tools.workspace.workspace_tools import workspace_tools, WORKSPACE_DIR
from tools.context_utils import limit_context_window

DEFAULT_ACCEPTANCE_THRESHOLD = 0.85
DEFAULT_METRIC_POLICY = "task_aware"

# Path injected into the pre-written ml/train.py so it can import module_4.auto_train
SRC_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

MODULE_4_SYSTEM_PROMPT = """You are "Module 4: The Data Scientist" in an automated xApp development pipeline.
A deterministic two-stage auto-training script (`ml/train.py`) has ALREADY been written
for you by the orchestrator. It runs a curated registry of sklearn algorithms (spot-check
with default params, then RandomizedSearchCV tuning of the top performers) and writes
`ml/evaluation_report.json` plus `ml/saved_model.pkl`.

DO NOT REWRITE OR EDIT `ml/train.py`. Your only job is to run it, verify the report,
and emit the final JSON block.

--- WORKFLOW ---
1. CREATE DIRECTORY: ensure `ml/` exists in the workspace (the script also creates it
   if missing).
2. EXECUTE: run `python3 ml/train.py`. If the script crashes (non-zero exit), read
   stderr — most failures here mean Module 3 produced bad data, NOT a script bug.
   Re-running won't help. Surface the error and stop.
3. VERIFY: run
   `python3 -c "import json; print(json.dumps(json.load(open('ml/evaluation_report.json')), indent=2)[:800])"`
   Confirm the report exists, parses, and contains the expected keys.
4. SAVE the terminal output to `log/module_4_ml.log`.

--- RESPONSE FORMAT ---
After step 4, emit the final JSON block. Use LITERAL values copied from
`ml/evaluation_report.json`; do NOT compute or call Python inside the block.

```json
{
  "ML_Model_Artifacts": {
    "model_path": "ml/saved_model.pkl",
    "technique_used": "string (e.g., 'RandomForestClassifier for Supervised_ML')",
    "expected_input_features": ["col1", "col2"],
    "best_metric_name": "f1 | f1_macro | neg_rmse | anomaly_f1 | anomaly_separation_advisory",
    "best_metric_value": 0.91,
    "threshold": 0.85,
    "threshold_met": true,
    "evaluation_report_path": "ml/evaluation_report.json"
  }
}
```
"""


_TRAIN_SCRIPT_TEMPLATE = '''"""Auto-generated by Module 4 orchestrator. Do not edit by hand."""
import os
import sys

# Make the framework's src/ importable so we can use the shared auto_train runner.
sys.path.insert(0, {src_root!r})

from module_4.auto_train import run_auto_training

if __name__ == "__main__":
    report = run_auto_training(
        train_path={train_path!r},
        test_path={test_path!r},
        threshold={threshold!r},
        cycle_type={cycle_type!r},
        report_path={report_path!r},
        model_path={model_path!r},
        metric_policy={metric_policy!r},
        label_column_hint={label_hint!r},
    )
    print(
        f"Best: {{report['technique_used']}} | "
        f"{{report['best_metric_name']}}={{report['best_metric_value']:.4f}} | "
        f"threshold_met={{report['threshold_met']}}"
    )
'''


def _write_train_script(
    train_data: str,
    test_data: str,
    threshold: float,
    cycle_type: str,
    metric_policy: str,
    label_hint: Optional[str],
) -> str:
    ml_dir = os.path.join(WORKSPACE_DIR, "ml")
    os.makedirs(ml_dir, exist_ok=True)
    script_path = os.path.join(ml_dir, "train.py")
    content = _TRAIN_SCRIPT_TEMPLATE.format(
        src_root=SRC_ROOT,
        train_path=train_data,
        test_path=test_data,
        threshold=float(threshold),
        cycle_type=cycle_type,
        report_path="ml/evaluation_report.json",
        model_path="ml/saved_model.pkl",
        metric_policy=metric_policy,
        label_hint=label_hint,
    )
    with open(script_path, "w") as f:
        f.write(content)
    return script_path

def get_llm():
    ollama_url = os.getenv("OLLAMA_URL", "http://localhost:11434")
    ollama_model = os.getenv("OLLAMA_MODEL", "llama3.1")
    return ChatOllama(model=ollama_model, base_url=ollama_url)

def _coerce_threshold(value: Any) -> float:
    try:
        threshold = float(value)
    except (TypeError, ValueError):
        return DEFAULT_ACCEPTANCE_THRESHOLD
    if threshold <= 0:
        return DEFAULT_ACCEPTANCE_THRESHOLD
    if threshold > 1:
        return threshold / 100.0 if threshold <= 100 else DEFAULT_ACCEPTANCE_THRESHOLD
    return threshold

def ensure_model_acceptance_defaults(blueprint: Dict[str, Any]) -> Dict[str, Any]:
    """Backfill model acceptance criteria so older blueprints remain valid."""
    intent = blueprint.setdefault("Intent_Blueprint", {})
    criteria = intent.get("model_acceptance_criteria")
    if not isinstance(criteria, dict):
        criteria = {}

    criteria["threshold"] = _coerce_threshold(criteria.get("threshold", DEFAULT_ACCEPTANCE_THRESHOLD))
    criteria["metric_policy"] = criteria.get("metric_policy") or DEFAULT_METRIC_POLICY
    criteria.setdefault(
        "metric_description_NL",
        "Task-aware model quality: supervised accuracy/F1, anomaly F1 for labeled anomaly tests, or reconstruction/separation quality for autoencoder-style workflows."
    )
    intent["model_acceptance_criteria"] = criteria
    return blueprint

def _finalize_ml_artifacts(artifacts: Dict[str, Any], blueprint: Dict[str, Any]) -> Dict[str, Any]:
    criteria = blueprint.get("Intent_Blueprint", {}).get("model_acceptance_criteria", {})
    threshold = _coerce_threshold(criteria.get("threshold", DEFAULT_ACCEPTANCE_THRESHOLD))
    artifacts.setdefault("model_path", "ml/saved_model.pkl")
    artifacts.setdefault("evaluation_report_path", "ml/evaluation_report.json")
    artifacts.setdefault("threshold", threshold)
    artifacts.setdefault("threshold_met", False)
    artifacts.setdefault("best_metric_name", "unknown")
    artifacts.setdefault("best_metric_value", None)
    artifacts.setdefault("expected_input_features", [])
    return artifacts

def _write_fallback_report(blueprint: Dict[str, Any], error_msg: str) -> None:
    """Write a minimal evaluation_report.json when the agent crashes or exhausts its limit."""
    criteria = blueprint.get("Intent_Blueprint", {}).get("model_acceptance_criteria", {})
    threshold = _coerce_threshold(criteria.get("threshold", DEFAULT_ACCEPTANCE_THRESHOLD))
    report = {
        "status": "AGENT_FAILED",
        "error": error_msg[:500],
        "threshold": threshold,
        "metric_policy": criteria.get("metric_policy", DEFAULT_METRIC_POLICY),
        "threshold_met": False,
        "best_metric_name": None,
        "best_metric_value": None,
        "technique_used": None,
        "expected_input_features": [],
        "evaluation_report_path": "ml/evaluation_report.json",
        "attempts": [],
        "note": "Module 4 agent did not complete. Increase ML_RECURSIVE_LIMIT or check logs."
    }
    ml_dir = os.path.join(WORKSPACE_DIR, "ml")
    os.makedirs(ml_dir, exist_ok=True)
    report_path = os.path.join(ml_dir, "evaluation_report.json")
    if not os.path.exists(report_path):
        with open(report_path, "w") as f:
            json.dump(report, f, indent=2)

def _recover_artifacts_from_workspace(blueprint: Dict[str, Any]) -> Dict[str, Any]:
    """Read ml/evaluation_report.json from workspace and populate ML_Model_Artifacts."""
    report_path = os.path.join(WORKSPACE_DIR, "ml", "evaluation_report.json")
    model_path = os.path.join(WORKSPACE_DIR, "ml", "saved_model.pkl")
    if not os.path.exists(report_path):
        return blueprint
    try:
        with open(report_path) as f:
            report = json.load(f)
        artifacts = {
            "model_path": "ml/saved_model.pkl" if os.path.exists(model_path) else None,
            "technique_used": report.get("technique_used"),
            "expected_input_features": report.get("expected_input_features", []),
            "best_metric_name": report.get("best_metric_name"),
            "best_metric_value": report.get("best_metric_value"),
            "threshold": report.get("threshold", DEFAULT_ACCEPTANCE_THRESHOLD),
            "threshold_met": report.get("threshold_met", False),
            "evaluation_report_path": "ml/evaluation_report.json",
        }
        blueprint["ML_Model_Artifacts"] = _finalize_ml_artifacts(artifacts, blueprint)
        print(f"Module 4: recovered artifacts from workspace — threshold_met={artifacts['threshold_met']}, metric={artifacts['best_metric_value']}")
    except Exception as e:
        print(f"Module 4: artifact recovery failed: {e}")
    return blueprint

def _extract_ml_context(blueprint: dict) -> dict:
    """Return only the fields needed for ML training."""
    return {
        "Intent_Blueprint": blueprint.get("Intent_Blueprint", {}),
        "Technical_Mapping": blueprint.get("Technical_Mapping", {}),
        "Data_Paths": blueprint.get("Data_Paths", {})
    }

def module_4_ml_dev_node(state: dict) -> dict:
    """Module 4: Trains an ML model and saves the artifact."""

    blueprint_state = copy.deepcopy(state.get("blueprint", {})) if isinstance(state.get("blueprint"), dict) else {}
    blueprint = ensure_model_acceptance_defaults(blueprint_state)

    data_paths = blueprint.get("Data_Paths", {})
    hist_data = data_paths.get("historical_training_data_path", "data/historical_training_data.csv")
    test_data = data_paths.get("test_data_path", "data/test_data.csv")
    label_hint = data_paths.get("test_label_column")
    criteria = blueprint.get("Intent_Blueprint", {}).get("model_acceptance_criteria", {})
    threshold = _coerce_threshold(criteria.get("threshold", DEFAULT_ACCEPTANCE_THRESHOLD))
    metric_policy = criteria.get("metric_policy", DEFAULT_METRIC_POLICY)
    cycle_type = blueprint.get("Intent_Blueprint", {}).get("cycle_Type", "Supervised_ML")

    # Deterministically pre-write ml/train.py so the LLM agent never re-invents the
    # algorithm code. The agent's job is only to run + verify.
    try:
        script_path = _write_train_script(
            train_data=hist_data,
            test_data=test_data,
            threshold=threshold,
            cycle_type=cycle_type,
            metric_policy=metric_policy,
            label_hint=label_hint,
        )
        print(f"Module 4: pre-wrote training script at {script_path}")
    except Exception as e:
        error_msg = f"Failed to pre-write ml/train.py: {e}"
        print(f"Module 4 Error: {error_msg}")
        _write_fallback_report(blueprint, error_msg)
        blueprint = _recover_artifacts_from_workspace(blueprint)
        return {
            "blueprint": blueprint,
            "messages": [AIMessage(content=error_msg)],
        }

    ml_context = _extract_ml_context(blueprint)

    prompt_content = (
        f"Here is the complete Blueprint:\n{json.dumps(ml_context, indent=2)}\n\n"
        f"Training data: `{hist_data}` | Test data: `{test_data}`\n"
        f"Acceptance threshold: `{threshold}` | Metric policy: `{metric_policy}` | "
        f"Cycle type: `{cycle_type}`\n\n"
        f"`ml/train.py` has already been written for you (a thin wrapper around the "
        f"shared two-stage auto-training runner). Do NOT modify or rewrite it. Just "
        f"run it, verify ml/evaluation_report.json, save terminal output to "
        f"log/module_4_ml.log, and emit the ML_Model_Artifacts JSON block."
    )

    llm = get_llm()
    ml_agent = create_react_agent(model=llm, tools=workspace_tools, prompt=MODULE_4_SYSTEM_PROMPT, pre_model_hook=limit_context_window)

    final_text = ""
    try:
        # ML_RECURSIVE_LIMIT defaults to 40; falls back to RECURSIVE_LIMIT if that env var is set higher
        recursion_limit = int(os.getenv("ML_RECURSIVE_LIMIT", max(80, int(os.getenv("RECURSIVE_LIMIT", 20)))))
        result = ml_agent.invoke(
            {"messages": [HumanMessage(content=prompt_content)]},
            {"recursion_limit": recursion_limit}
        )
        final_text = result["messages"][-1].content
    except Exception as e:
        error_msg = str(e)
        print(f"Module 4 Error (ML Training): {error_msg}")
        _write_fallback_report(blueprint, error_msg)
        blueprint = _recover_artifacts_from_workspace(blueprint)
        return {
            "blueprint": blueprint,
            "messages": [AIMessage(content=f"ML Training agent failed: {error_msg}")]
        }

    # Try to extract ML_Model_Artifacts from the agent's final JSON block
    json_match = re.search(r'```json\s*(.*?)\s*```', final_text, re.DOTALL)
    if json_match:
        try:
            parsed = json.loads(json_match.group(1))
            ml_artifacts = _finalize_ml_artifacts(parsed.get("ML_Model_Artifacts", {}), blueprint)
            blueprint["ML_Model_Artifacts"] = ml_artifacts
        except json.JSONDecodeError:
            print("Module 4: failed to parse JSON from agent output, recovering from workspace.")
            blueprint = _recover_artifacts_from_workspace(blueprint)
    else:
        # Agent finished but didn't emit JSON — read the report file directly
        print("Module 4: no JSON block in agent output, recovering from workspace.")
        blueprint = _recover_artifacts_from_workspace(blueprint)

    # Return a summary to keep main state clean
    met = blueprint.get("ML_Model_Artifacts", {}).get("threshold_met", False)
    val = blueprint.get("ML_Model_Artifacts", {}).get("best_metric_value", 0)
    summary = f"Module 4: ML Training complete. Threshold met: {met} (Metric: {val:.3f})."

    return {
        "blueprint": blueprint,
        "messages": [AIMessage(content=summary)]
    }
