openapi: 3.0.1
info:
  title: O1 Registration Notification
  version: 17.00.00
  description: >-
    OAS 3.0.1 definition of the O1 Registration Notification
    
    Copyright 2025 O-RAN ALLIANCE e.V.
    Licensed under the Standards Collaboration
    Copyright License Version 1.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    https://www.o-ran.org/sccl
externalDocs:
  description: O-RAN O1 Interface Specification
  url: https://specifications.o-ran.org/
paths:
  {}
components:
  schemas:
    NotifyO1Registration:
      allOf:
        - $ref: 'O1_Notifications.yaml#/components/schemas/NotificationHeader'
        - type: object
          required:
            - oamIpAddress
          properties:
            serialNumber:
              type: string
            vendorName:
              type: string
            oamIpAddress:
              oneOf:
                - $ref: '//forge.3gpp.org/rep/all/5G_APIs/-/raw/REL-18/TS28623_ComDefs.yaml#/components/schemas/Ipv4Addr'
                - $ref: '//forge.3gpp.org/rep/all/5G_APIs/-/raw/REL-18/TS28623_ComDefs.yaml#/components/schemas/Ipv6Addr'
            macAddress:
              type: string
            unitFamily:
              type: string
            unitType:
              type: string
            modelNumber:
              type: string
            softwareVersion:
              type: string
            softwareName:
              type: string
            restartReason:
              type: string
            manufactureDate:
              $ref: '//forge.3gpp.org/rep/all/5G_APIs/-/raw/REL-18/TS28623_ComDefs.yaml#/components/schemas/DateTime'
            lastServiceDate:
              $ref: '//forge.3gpp.org/rep/all/5G_APIs/-/raw/REL-18/TS28623_ComDefs.yaml#/components/schemas/DateTime'
            additionalInformation:
              $ref: '//forge.3gpp.org/rep/all/5G_APIs/-/raw/REL-18/TS28623_ComDefs.yaml#/components/schemas/AttributeNameValuePairSet'
