# flexric:latest
FROM ubuntu:jammy AS ran-flexric

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes && \
    DEBIAN_FRONTEND=noninteractive apt-get install --yes \
       build-essential \
       libsctp-dev \
       git \
       wget \
       tar \
       m4 \
       automake \
       libtool \
       python3 \
       cmake \
       cmake-curses-gui \
       bison \
       flex \
       gdb \
       libpcre2-dev \
       python3-dev \
       python3-pip \
       gcc-12 \
       g++-12 \
       mold \
       nano \
       iputils-ping \
       curl \
       ninja-build && \
    apt-get clean

RUN python3 -m pip install --no-cache-dir \
    prometheus-client==0.20.0

WORKDIR /opt

#swig
RUN git clone https://github.com/swig/swig.git /opt/swig
RUN cd swig && git checkout release-4.1 && ./autogen.sh && ./configure --prefix=/usr/ && make -j$(nproc) && make install

RUN rm -rf /tmp/asn1c && \
    git clone https://github.com/mouse07410/asn1c /tmp/asn1c && \
    cd /tmp/asn1c && \
    git checkout 940dd5fa9f3917913fd487b13dfddfacd0ded06e && \
    # Showing which version is used
    git log -n1 && \
    autoreconf -iv && \
    ./configure --prefix /opt/asn1c/ && \
    make -j$(nproc) && \
    make install

WORKDIR /

ARG E2AP_VERSION=E2AP_V3
ARG KPM_VERSION=KPM_V3_00

#flexric
RUN git clone https://gitlab.eurecom.fr/mosaic5g/flexric /flexric
WORKDIR /flexric
RUN git checkout dev 
RUN mkdir build && \
    cd build && \
    cmake -GNinja -DCMAKE_BUILD_TYPE=Release \
          -DE2AP_VERSION=$E2AP_VERSION \
          -DKPM_VERSION=$KPM_VERSION \
          -DXAPP_MULTILANGUAGE=ON \
          -DCMAKE_C_COMPILER=gcc-12 \
          -DCMAKE_CXX_COMPILER=g++-12 .. && \
    ninja && \
    ninja install


COPY ./xapps /flexric/build/examples/xApp/python3/

COPY ./healthcheck/xapp.sh /opt/healthcheck.sh
RUN chmod +x /opt/healthcheck.sh

WORKDIR /
COPY ./entrypoints/xapp.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]